import type { Metadata } from "next";

import { Inter } from "next/font/google";
import { comment } from "postcss";
import "./globals.css";
import SideBar from "Components/SideBar/SideBar";
import SessionProvider from "Components/Utility/SessionProvider";
import { getServerSession } from "next-auth/next";
import { authOptions } from "pages/api/auth/[...nextauth]";
import Login from "Components/Auth/Login/Login";
import ClientProvider from "Components/Notification/ClientProvider";
// import { authHandler } from "../../FireBase/FireBase";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);
  // const session = await authHandler();

  console.log(session);

  return (
    <html lang="en">
      <body>
        <SessionProvider session={session}>
          {!session ? (
            <Login />
          ) : (
            <div className="flex">
              {
                // TODO : SideBar */
              }
              <div className="bg-[#202123] max-w-xs h-screen overflow-y-auto md:min-w-[20rem]">
                <SideBar />
              </div>

              {
                // TODO : ClientProvider - Notification */
                <ClientProvider />
              }
              <div className="bg-[#343541] flex-1">{children}</div>
            </div>
          )}
        </SessionProvider>
      </body>
    </html>
  );
}
